In [1]:
import numpy as np

In [4]:
import pandas as pd

In [6]:
my_list=[1,4,5,67,89]

arr=np.array(my_list)

In [7]:
print(arr)

[ 1  4  5 67 89]


In [8]:
type(arr)

numpy.ndarray

In [38]:
my_list1=[2,45,51,78,2,67]
my_list2=[4,5,63,8,889,78]
my_list3=[8,56,69,34,6,64]

arr=np.array([my_list1,my_list2,my_list3])

In [39]:
arr

array([[  2,  45,  51,  78,   2,  67],
       [  4,   5,  63,   8, 889,  78],
       [  8,  56,  69,  34,   6,  64]])

In [40]:
type(arr)

numpy.ndarray

In [41]:
arr.shape

(3, 6)

In [42]:
# #Indexing


In [43]:
[3,4,5,45,67,87,69]
arr=np.array([3,4,5,45,67,87,69])

In [44]:
arr[3]

45

In [45]:
arr=np.array([my_list1,my_list2,my_list3])

In [46]:
arr

array([[  2,  45,  51,  78,   2,  67],
       [  4,   5,  63,   8, 889,  78],
       [  8,  56,  69,  34,   6,  64]])

In [54]:
arr[1:,:2]

array([[ 4,  5],
       [ 8, 56]])

In [55]:
arr[:,3:]

array([[ 78,   2,  67],
       [  8, 889,  78],
       [ 34,   6,  64]])

In [56]:
arr

array([[  2,  45,  51,  78,   2,  67],
       [  4,   5,  63,   8, 889,  78],
       [  8,  56,  69,  34,   6,  64]])

In [69]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
arr=np.arange(0,10).reshape(2,5)

In [71]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
arr*arr

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [81]:
np.random.rand(3,3)

array([[0.88660186, 0.60832298, 0.96842368],
       [0.97715926, 0.29800004, 0.88458462],
       [0.86604669, 0.19995001, 0.30186519]])

In [86]:
arr_ex=np.random.rand(4,5)

In [87]:
arr_ex

array([[0.64284348, 0.11091604, 0.36620946, 0.80918238, 0.2262023 ],
       [0.80183594, 0.38033434, 0.7193697 , 0.71318399, 0.96434592],
       [0.19591136, 0.33898746, 0.11398276, 0.62248722, 0.79935257],
       [0.53368338, 0.01639646, 0.02142621, 0.07315787, 0.27078102]])

In [88]:
import seaborn as sns 